### ISSUE TITLE
Error setting MaxKnotNum_Trend to zero

### ISSUE THREAD

**Issue by jacobmardian** [zhaokg/Rbeast#1]
I would like to set MaxKnotNum_Trend to zero to examine seasonal changes only. When I do this I get the error "r2<r1:There must be something wrong!" before RStudio crashes.

**Comment by mcneilsm** [comment]
Hi jacobmardian, were you able to figure out how to set MaxKnotNum_Trend to zero? I am in a similar position where I would like to set MaxKnotNum_Season to zero to examine trend changes only, but I get the same error as you did.

**Comment by zhaokg** [comment]
Hi jacobmardian and mcneilsm;  Sorry for not get a chance to see your issue report earlier and for my belated reply. Not sure if my reply is still relevant to you (probably not. Jacob, thanks for testing out BEAST in your rse paper), although I saw your paper earlier than seeing your issue here. 


Also, thanks a lot for all the feedbacks. The original version of Rbeast posted 3 years was too buggy, failing to handle many edge cases and often leading to misinterpretation of results by non-Bayesian users. Regardless, in the new version, I corrected for the cases. Here are some examples/addiations:

** It is possible to fit a trend-only model if the data has no periodic component at all
```R
library(Rbeast)
o=beast(Nile, season='none')
plot(o)
```
** It is possible to set the seasonMaxKnotNum=0 or trendMaxKnotNum=0

```R
library(Rbeast)
o=beast(Nile, season='none', tcp.minmax=c(0,0) )  #set the min and max number of trend changepoints to zero, which basically fit a global trend model. Similarly you can also set scp.minmax=c(0,0) if the time series has a seasonal component
plot(o)
```

Once again, thanks a lot for your valuable feedbacks. Sorry for overlooking your report here.
