### ISSUE TITLE
Old releases are being deleted from PyPI

### ISSUE THREAD

**Issue by lygiaagueda** [zhaokg/Rbeast#35]
With each new release, the previous ones are deleted from PyPI. Is there any reason why this is being done?

**Comment by zhaokg** [comment]
Thanks for asking. It is not an easy question to answer. But to make it simple, I removed the old releases because I just put too many versions there and I want potential users to use the latest release.

The frequent update is mostly because the program is written in C/C++. My challenge is to use the same C code and maintain it  for three computing environment R, Python, and Matlab. Given it is C/C++, there are numerous factors controlling the compilation of the C code:

- Software environments:  R, Python, Matlab, and Octave. Each of them have different versions (e.g., Python 3.7 - 3.11); even worse, for the same version, the numpy package needed in BEAST has numerous veresions.
- C complier: gcc-11, gcc-12,gcc-13, gcc-14, clang-asan, clang16, clang17, clang18, clang19, MSVC, and Cracle solaris C, llvm-gcc,  and MinGW-gcc
- C standards: C99, C11, C19, and C23
- CPU type： intel x86, intel x64/amd64. arm32, arm64, PowerPC,  and M1-3
- OS：  WIndows (32 vs 64), Linux (Ubuntu, Fedora, and etc), MacOS-Intel, MacOS-Apple-Silicon

Apparently, these combinations make my code very vulnerable and buggy for some combinations of these factors. For sure, I don't have all the machines to test it (I have only a Windows machine for my work). Sometimes I have to rely on users to report the problems on a particular platform.   In almost all the cases, these bugs have nothing to with the BEAST algorithm code; they were rather some system-specific glitches.

If there are some twists to the APIs, I normally keep track of the changes for the R and Matlab versions (e.g., https://cran.r-project.org/web/packages/Rbeast/news/news.html) but not for the Python versions. 
Because R, Python, and Matlab have different mechanisms for publishing packages (e.g., for R, it is recommended/required to update the package in no less than 2 months), it is hard to synchronize the versions between the R, Matlab, and Python packages.  With that said, the Python version is the hardest to maintain because of the many different versions of Python and Numpy.   Each release will generate 33 binary wheel versions.  So, another reason for removing the old releases is that I don't  want to waste storage space on PyPi (this was the initial reason when I first removed old releases).

Sorry for my mumbling here. Again, if there is any interest in giving the package a try, please use the latest version.  Please let me know if you have any more or specific questions.

**Comment by julio-cmdr** [comment]
Hi @zhaokg. It's very important to keep the library updated. However, please don't remove the old versions from PyPI. In software development, it's recommended to fix all the library versions being used. This is a good practice because it ensures that the software operation won't be affected by external updates. I'm working on a project using Rbeast. Each time we update the library version, we must review all our model metrics. Moreover, I'm concerned that with a major modification to the library, we might lose compatibility with other libraries and be forced to abandon Rbeast.

**Comment by zhaokg** [comment]
> Hi @zhaokg. It's very important to keep the library updated. However, please don't remove the old versions from PyPI. In software development, it's recommended to fix all the library versions being used. This is a good practice because it ensures that the software operation won't be affected by external updates. I'm working on a project using Rbeast. Each time we update the library version, we must review all our model metrics. Moreover, I'm concerned that with a major modification to the library, we might lose compatibility with other libraries and be forced to abandon Rbeast.

Dear julio-cmr, Thanks for the important and valuable feedbacks. Definitely your advice is well taken on my end. I will keep all the major releases on PyPi, especially if there are some minor feature changes, and I may have to still remove some redundant releases if the changes are just for correcting for spelling errors or revising readme. md (Yes, most of the releases I put on PyPI is for updating Readme.md only, which has nothing to do with the code.)

**Comment by zhaokg** [comment]
Appreciate again for this useful feedback. I will close this issue for now. Free free to re-open it or create a new one if any related problems arise. Last but not the last, thanks again for giving Rbeast  a try!
